---
title: "Untitled"
description: |
  Some of the data correlations that I found
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---
---
title: "HomeworkStress"
author: "Daniel Wang"
date: "17/06/2021"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rvest)
library(janitor)
```


```{r get data, echo = FALSE, include=FALSE}
raw_data <- read_csv("responses.csv") %>% 
  clean_names()
raw_data

time_frames <- c('before' = "Before Covid-19", 'after' = "During Covid-19")

clean_data2 <- read_csv("clean_data.csv") %>% 
  mutate(time_frame_f = factor(time_frame, c("before", "after"))) %>% 
  mutate(environment = factor(environment, c("Physical","Hybrid","Virtual")))



clean_data <- raw_data %>% 
  select(before_homework_stress, now_homework_stress) %>% 
  pivot_longer(names_to = "time_frame", values_to = "stress", cols = before_homework_stress:now_homework_stress)
 
relationship_data <- raw_data %>% 
  mutate(change_hwk_stress = now_homework_stress - before_homework_stress) %>% 
  pivot_longer(names_to = "relationship_type", values_to = "change", cols = c(family_relationships, friend_relationships))

```

``` {r create plots, echo = FALSE}
plot_data <- clean_data %>% 
  ggplot(aes(x = stress, fill = time_frame))+
  geom_bar()+
  facet_wrap(~time_frame)+
  theme_classic()+
  labs(title = "Stress Levels Experienced by Students Before and After Covid-19", subtitle = "There were higher stress levels experienced during Covid-19", x = "Stress Levels", y = "Count", fill = "Time Period")

plot_data2 <- clean_data2 %>% 
  ggplot(aes(classwork_stress))+
  geom_bar()+
  facet_wrap(.~time_frame_f+environment)

plot_data3 <- clean_data2 %>% 
  ggplot(aes(x = homework_hours, y = homework_stress))+
  geom_jitter()+
  geom_smooth(method = "loess", formula = y ~ x)+
  facet_wrap(.~time_frame_f)


```

```{r}
plot_data4 <- clean_data2 %>% 
  ggplot(aes(x = homework_stress))+
  geom_density()+
  facet_wrap(.~time_frame_f)

plot_data5 <- clean_data2 %>% 
  ggplot(aes(x = homework_stress, fill = time_frame))+
  geom_bar(show.legend = FALSE)+
  facet_wrap(~time_frame_f, labeller = as_labeller(time_frames))+
    labs(title = "Stress Levels Experienced by Students Before and After Covid-19", subtitle = "There were higher stress levels experienced during Covid-19", x = "Stress Levels", y = "Count", fill = "", legend.x = NULL)

plot_data6 <- clean_data2 %>% 
  ggplot(aes(x = classwork_stress, fill = time_frame))+
  geom_bar(show.legend = FALSE)+
  facet_wrap(~time_frame_f, labeller = as_labeller(time_frames))+
    labs(title = "Stress Levels Experienced by Students Before and After Covid-19", subtitle = "There were higher stress levels experienced during Covid-19", x = "Stress Levels", y = "Count", fill = "", legend.x = NULL)

plot_data7 <- clean_data2 %>% 
  pivot_longer(names_to = "stress_type", values_to = "stress_level", cols = c(classwork_stress,homework_stress)) %>% 
  ggplot(aes(x = stress_level, fill = stress_type))+
  geom_bar(position = "dodge")+
  facet_wrap(~time_frame_f, labeller = as_labeller(time_frames))+
    labs(title = "Stress Levels Experienced by Students Before and After Covid-19", subtitle = "There were higher stress levels experienced during Covid-19", x = "Stress Levels", y = "Count", fill = "")

plot_data8 <- clean_data2 %>% 
  pivot_longer(names_to = "stress_type", values_to = "stress_level", cols = c(classwork_stress,homework_stress)) %>% 
  ggplot(aes(x = stress_level, fill = stress_type))+
  geom_density(alpha = 0.5)+
  facet_wrap(~time_frame_f, labeller = as_labeller(time_frames))+
    labs(title = "Stress Levels Experienced by Students Before and During Covid-19", subtitle = "There were higher stress levels experienced during Covid-19", x = "Stress Levels", y = "Count", fill = "")

plot_data5
plot_data6
plot_data7
plot_data8
```

```{r echo=FALSE}
#change
relationship_data$change_hwk_stress %>% 
  table()

# 
# relationship_data %>% 
#   drop_na(change_hwk_stress) %>% 
#   mutate(change_hwk_stress = as.character(change_hwk_stress)) %>% 
#   filter((change_hwk_stress %in% c("2","1"))) %>% 
#   ggplot(aes(x = change, y = relationship_type, fill = change_hwk_stress))+
#   stat_slab()

relationship_data %>%
  ggplot(aes(x = change_hwk_stress))+
  geom_histogram()+
  facet_wrap(~gender)
```


```{r, echo = FALSE}
plot_data
plot_data2
plot_data3
plot_data4
```


